# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('usarname', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShawPark',
            fields=[
                ('parkid', models.IntegerField(primary_key=True, serialize=False)),
                ('lon', models.FloatField(default=73.7236456)),
                ('let', models.FloatField(default=24.5968106)),
                ('tot', models.IntegerField(default=8)),
                ('avail', models.IntegerField(default=4)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('givenplot', models.IntegerField(default=0)),
                ('plotid', models.IntegerField(primary_key=True, serialize=False)),
                ('userpin', models.IntegerField()),
            ],
        ),
    ]
