# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0003_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='userpin',
            field=models.IntegerField(),
        ),
    ]
