# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0004_auto_20171202_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shawpark',
            name='leti',
        ),
        migrations.RemoveField(
            model_name='shawpark',
            name='logi',
        ),
        migrations.AddField(
            model_name='shawpark',
            name='avail',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='shawpark',
            name='let',
            field=models.FloatField(default=24.5968106),
        ),
        migrations.AddField(
            model_name='shawpark',
            name='lon',
            field=models.FloatField(default=73.7236456),
        ),
        migrations.AddField(
            model_name='shawpark',
            name='tot',
            field=models.IntegerField(default=8),
        ),
    ]
